sodapoppin/2020-10/778540089_jackbox_party_pack_(with_sodapoppin)_-_oct_22,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/778540089_jackbox_party_pack_(with_sodapoppin)_-_oct_22,_2020.mp4
  link: https://youtu.be/E6UEIPiSsjY
  title: Jackbox Party Pack (with sodapoppin) - Oct 22, 2020
sodapoppin/2020-10/778540089_playing_vr_amoung_us!_(sodapoppin)_-_oct_22,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/778540089_playing_vr_amoung_us!_(sodapoppin)_-_oct_22,_2020.mp4
  link: https://youtu.be/0aHZUmghmwE
  title: Playing VR Amoung Us! (sodapoppin) - Oct 22, 2020
sodapoppin/2020-10/778540089_watching_the_final_presidential_debates_(with_sodapoppin):
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/778540089_watching_the_final_presidential_debates_(with_sodapoppin).mp4
  link: https://youtu.be/SyU371iRGNE
  title: Watching the Final Presidential Debates (with sodapoppin)
sodapoppin/2020-10/779582841_friday_dungeons_&_dragons_(flamewrath_sodapoppin)_-_oct_23,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/779582841_friday_dungeons_&_dragons_(flamewrath_sodapoppin)_-_oct_23,_2020.mp4
  link: https://youtu.be/_CwdptcKSQ0
  title: Friday Dungeons & Dragons (flamewrath sodapoppin) - Oct 23, 2020
sodapoppin/2020-10/780773240_absinth_(horror)_-_shitshow_saturday_-_oct_24,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/780773240_absinth_(horror)_-_shitshow_saturday_-_oct_24,_2020.mp4
  link: https://youtu.be/6-3FgBuHP9k
  title: Absinth (horror) - Shitshow Saturday - Oct 24, 2020
sodapoppin/2020-10/780773240_in_silence_(multi-player_horror)_-_shitshow_saturday_-_oct_24,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/780773240_in_silence_(multi-player_horror)_-_shitshow_saturday_-_oct_24,_2020.mp4
  link: https://youtu.be/kbtcqvdOiO0
  title: In Silence (multi-player horror) - Shitshow Saturday - Oct 24, 2020
sodapoppin/2020-10/780773240_kohate_(sci-fi_horror)_-_shitshow_saturday_-_oct_24,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/780773240_kohate_(sci-fi_horror)_-_shitshow_saturday_-_oct_24,_2020.mp4
  link: https://youtu.be/xPsz4JTFJqA
  title: Kohate (sci-fi horror) - Shitshow Saturday - Oct 24, 2020
sodapoppin/2020-10/780773240_murder_house_-_part_1_(sodapoppin)_shitshow_saturday_-_oct_24,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/780773240_murder_house_-_part_1_(sodapoppin)_shitshow_saturday_-_oct_24,_2020.mp4
  link: https://youtu.be/qlfIE3s0vTw
  title: Murder House - Part 1 (sodapoppin) Shitshow Saturday - Oct 24, 2020
sodapoppin/2020-10/781906925_watching_random_videos_(sodapoppin)_-_oct_25,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/781906925_watching_random_videos_(sodapoppin)_-_oct_25,_2020.mp4
  link: https://youtu.be/UAZg-5ODcUc
  title: Watching Random Videos (sodapoppin) - Oct 25, 2020
sodapoppin/2020-10/784892480_ghostrunner_(new_cyberpunk_game,_sodapoppin)_-_oct_28,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/784892480_ghostrunner_(new_cyberpunk_game,_sodapoppin)_-_oct_28,_2020.mp4
  link: https://youtu.be/VE5du7orvag
  title: Ghostrunner (new cyberpunk game, sodapoppin) - Oct 28, 2020
sodapoppin/2020-10/784892480_murder_house_-_part_2_(sodapoppin)_-_oct_28,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/784892480_murder_house_-_part_2_(sodapoppin)_-_oct_28,_2020.mp4
  link: https://youtu.be/tnsrU_swVbM
  title: Murder House - Part 2 (sodapoppin) - Oct 28, 2020
sodapoppin/2020-10/785911409_teardown_heists_sandbox_voxel_(sodapoppin)_-_oct_29,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/785911409_teardown_heists_sandbox_voxel_(sodapoppin)_-_oct_29,_2020.mp4
  link: https://youtu.be/2OFAqdprUw8
  title: Teardown Heists Sandbox Voxel (sodapoppin) - Oct 29, 2020
sodapoppin/2020-10/786850186_friday_dungeons_&_dragons_(flamewrath_sodapoppin)_-_oct_30,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/786850186_friday_dungeons_&_dragons_(flamewrath_sodapoppin)_-_oct_30,_2020.mp4
  link: https://youtu.be/b3Uej6NvWdQ
  title: Friday Dungeons & Dragons (flamewrath sodapoppin) - Oct 30, 2020
sodapoppin/2020-10/788070916_dead_by_daylight_-_(sodapoppin)_oct_31,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/788070916_dead_by_daylight_-_(sodapoppin)_oct_31,_2020.mp4
  link: https://youtu.be/w11jWPHzmDg
  title: Dead by Daylight - (sodapoppin) Oct 31, 2020
sodapoppin/2020-10/788070916_friday_the_13th_with_friends!_(sodapoppin)_-_oct_31,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/788070916_friday_the_13th_with_friends!_(sodapoppin)_-_oct_31,_2020.mp4
  link: https://youtu.be/TVwKa_Fqjx0
  title: Friday the 13th with Friends! (sodapoppin) - Oct 31, 2020
sodapoppin/2020-10/788070916_scp_secret_laboratory_with_friends!_(sodapoppin)_-_oct_31,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-10/788070916_scp_secret_laboratory_with_friends!_(sodapoppin)_-_oct_31,_2020.mp4
  link: https://youtu.be/H5GMLUDolEc
  title: SCP Secret Laboratory with Friends! (sodapoppin) - Oct 31, 2020
sodapoppin/2020-11/789136667_soda_plays_visage_chapters_1-3_-_nov_1,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/789136667_soda_plays_visage_chapters_1-3_-_nov_1,_2020.mp4
  link: https://youtu.be/Ybgb3qwzM1w
  title: Soda Plays Visage Chapters 1-3 - Nov 1, 2020
sodapoppin/2020-11/789136667_sodapoppin_merch_store_shirt_competition_-_nov_1,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/789136667_sodapoppin_merch_store_shirt_competition_-_nov_1,_2020.mp4
  link: https://youtu.be/aCvhAXOZ1zE
  title: Sodapoppin Merch Store Shirt Competition - Nov 1, 2020
sodapoppin/2020-11/791075346_for_the_king_single_player_(sodapoppin)_-_nov_3,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/791075346_for_the_king_single_player_(sodapoppin)_-_nov_3,_2020.mp4
  link: https://youtu.be/28S6th9IfjQ
  title: For The King Single Player (sodapoppin) - Nov 3, 2020
sodapoppin/2020-11/791075346_sodapoppin_plays_pacer_(racing_game)_-_nov_3,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/791075346_sodapoppin_plays_pacer_(racing_game)_-_nov_3,_2020.mp4
  link: https://youtu.be/ujO6V_hq24I
  title: Sodapoppin Plays Pacer (racing game) - Nov 3, 2020
sodapoppin/2020-11/791075346_stoneshard_part_1_(sodapoppin)_-_nov_3,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/791075346_stoneshard_part_1_(sodapoppin)_-_nov_3,_2020.mp4
  link: https://youtu.be/1GALPII-HS0
  title: Stoneshard Part 1 (sodapoppin) - Nov 3, 2020
sodapoppin/2020-11/791075346_visage_final_chapter_playthrough_(sodapoppin)_-_nov_3,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/791075346_visage_final_chapter_playthrough_(sodapoppin)_-_nov_3,_2020.mp4
  link: ''
  title: Visage Final Chapter Playthrough (sodapoppin) - Nov 3, 2020
sodapoppin/2020-11/792109101_sodapoppin_plays_ergastulum_(horror,_jump_scares)_-_nov_4,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/792109101_sodapoppin_plays_ergastulum_(horror,_jump_scares)_-_nov_4,_2020.mp4
  link: ''
  title: Sodapoppin Plays Ergastulum (horror, jump scares) - Nov 4, 2020
sodapoppin/2020-11/792109101_sodapoppin_plays_risk_of_rain_2_-_nov_4,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/792109101_sodapoppin_plays_risk_of_rain_2_-_nov_4,_2020.mp4
  link: https://youtu.be/hmjzaWWyXjE
  title: Sodapoppin Plays Risk of Rain 2 - Nov 4, 2020
sodapoppin/2020-11/792109101_stoneshard_part_2_(sodapoppin)_-_nov_4,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/792109101_stoneshard_part_2_(sodapoppin)_-_nov_4,_2020.mp4
  link: https://youtu.be/Vyn4p5K9TRw
  title: Stoneshard Part 2 (sodapoppin) - Nov 4, 2020
sodapoppin/2020-11/793136142_sodapoppin_plays_risk_of_rain_2_(sodapoppin)_-_nov_5,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/793136142_sodapoppin_plays_risk_of_rain_2_(sodapoppin)_-_nov_5,_2020.mp4
  link: https://youtu.be/idUjVOZd4QU
  title: Sodapoppin Plays Risk of Rain 2 (sodapoppin) - Nov 5, 2020
sodapoppin/2020-11/793136142_stoneshard_part_3_(sodapoppin)_-_nov_5,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/793136142_stoneshard_part_3_(sodapoppin)_-_nov_5,_2020.mp4
  link: https://youtu.be/mHCN7GTT7cc
  title: Stoneshard Part 3 (sodapoppin) - Nov 5, 2020
sodapoppin/2020-11/793136142_vrchat_videos_with_raid_trying_to_avoid_dmca_(sodapoppin)_-_nov_5,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/793136142_vrchat_videos_with_raid_trying_to_avoid_dmca_(sodapoppin)_-_nov_5,_2020.mp4
  link: https://youtu.be/UVM8hiNXBHE
  title: VRChat Videos with Raid Trying to Avoid DMCA (sodapoppin) - Nov 5, 2020
sodapoppin/2020-11/794159919_friday_dungeons_&_dragons_(flamewrath_sodapoppin)_-_nov_6,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/794159919_friday_dungeons_&_dragons_(flamewrath_sodapoppin)_-_nov_6,_2020.mp4
  link: https://youtu.be/7ovVMI5-Pok
  title: Friday Dungeons & Dragons (flamewrath sodapoppin) - Nov 6, 2020
sodapoppin/2020-11/794159919_vrchat_with_happythoughts_(sodapoppin)_-_nov_6,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/794159919_vrchat_with_happythoughts_(sodapoppin)_-_nov_6,_2020.mp4
  link: https://youtu.be/JL3GJ-5gThQ
  title: VRChat with Happythoughts (sodapoppin) - Nov 6, 2020
sodapoppin/2020-11/795420047_dead_by_daylight_(sodapoppin)_-_nov_7,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/795420047_dead_by_daylight_(sodapoppin)_-_nov_7,_2020.mp4
  link: https://youtu.be/xFqaolxi_NU
  title: Dead by Daylight (sodapoppin) - Nov 7, 2020
sodapoppin/2020-11/795420047_sodapoppin_plays_coldside_(indie_horror)_-_shitshow_saturday_-_nov_7,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/795420047_sodapoppin_plays_coldside_(indie_horror)_-_shitshow_saturday_-_nov_7,_2020.mp4
  link: https://youtu.be/1bRfu4vWB2k
  title: Sodapoppin Plays Coldside (indie horror) - Shitshow Saturday - Nov 7, 2020
sodapoppin/2020-11/795420047_sodapoppin_plays_gone_golfing_(indie_putt_putt_golf_horror)_-_shitshow_saturday_-_nov_7,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/795420047_sodapoppin_plays_gone_golfing_(indie_putt_putt_golf_horror)_-_shitshow_saturday_-_nov_7,_2020.mp4
  link: https://youtu.be/RzMRMy4kjHc
  title: Sodapoppin Plays Gone Golfing (indie putt putt golf horror) - Shitshow Saturday
    - Nov 7, 2020
sodapoppin/2020-11/795420047_sodapoppin_plays_perfect_vermin_-_shitshow_saturday_-_nov_7,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/795420047_sodapoppin_plays_perfect_vermin_-_shitshow_saturday_-_nov_7,_2020.mp4
  link: https://youtu.be/47Jxu4b1ZHU
  title: Sodapoppin Plays Perfect Vermin - Shitshow Saturday - Nov 7, 2020
sodapoppin/2020-11/795420047_sodapoppin_plays_woodle_tree_adventure_-_shitshow_saturday_-_nov_7,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/795420047_sodapoppin_plays_woodle_tree_adventure_-_shitshow_saturday_-_nov_7,_2020.mp4
  link: https://youtu.be/OVsHnnor_iU
  title: Sodapoppin Plays Woodle Tree Adventure - Shitshow Saturday - Nov 7, 2020
sodapoppin/2020-11/795420047_training_happythoughts_on_worms_w.m.d_-_nov_7,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/795420047_training_happythoughts_on_worms_w.m.d_-_nov_7,_2020.mp4
  link: https://youtu.be/L6cWUKBgL5o
  title: Training Happythoughts on Worms W.M.D - Nov 7, 2020
sodapoppin/2020-11/795420047_watching_scp_videos_(sodapoppin)_-_nov_7,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/795420047_watching_scp_videos_(sodapoppin)_-_nov_7,_2020.mp4
  link: https://youtu.be/YnH9M002JJU
  title: Watching SCP Videos (sodapoppin) - Nov 7, 2020
sodapoppin/2020-11/795769633_sodapoppin_reviews_wines_-_nov_7,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/795769633_sodapoppin_reviews_wines_-_nov_7,_2020.mp4
  link: https://youtu.be/oZgFeyQcBTw
  title: Sodapoppin Reviews Wines - Nov 7, 2020
sodapoppin/2020-11/795769633_vrchat_and_warcraft_3_(sodapoppin)_-_nov_7,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/795769633_vrchat_and_warcraft_3_(sodapoppin)_-_nov_7,_2020.mp4
  link: https://youtu.be/8Dz_Wgua-gI
  title: VRChat and Warcraft 3 (sodapoppin) - Nov 7, 2020
sodapoppin/2020-11/796413809_mute_vs_mute_worms_battle_(sodapoppin)_-_nov_8,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/796413809_mute_vs_mute_worms_battle_(sodapoppin)_-_nov_8,_2020.mp4
  link: https://youtu.be/UXxiwhAhbGI
  title: Mute vs Mute Worms Battle (sodapoppin) - Nov 8, 2020
sodapoppin/2020-11/796413809_sodapoppin_plays_ai_dungeon_-_nov_8,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/796413809_sodapoppin_plays_ai_dungeon_-_nov_8,_2020.mp4
  link: https://youtu.be/Jr2flpcwpgE
  title: Sodapoppin Plays AI Dungeon - Nov 8, 2020
sodapoppin/2020-11/797499989_sodapoppin_plays_ai_dungeon_(part_2)_-_nov_9,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/797499989_sodapoppin_plays_ai_dungeon_(part_2)_-_nov_9,_2020.mp4
  link: https://youtu.be/Ow351HXD-PA
  title: Sodapoppin Plays AI Dungeon (part 2) - Nov 9, 2020
sodapoppin/2020-11/797499989_sodapoppin_plays_noita_(with_twitch_chat_voting)_-_nov_9,_2020:
  file: D:\twitch_vod_creator/../data_rendered/sodapoppin/2020-11/797499989_sodapoppin_plays_noita_(with_twitch_chat_voting)_-_nov_9,_2020.mp4
  link: https://youtu.be/0nUfs4yT7Ro
  title: Sodapoppin Plays Noita (with twitch chat voting) - Nov 9, 2020
