
# ===========================================
# ===========================================


- video: sevadus/2020-10/782398211
  title: "Discussing Twitch VODs (part 1) - Sevadus - Oct. 26, 2020"
  t_start: "00:11:49,01:26:04,01:48:14"
  t_end: "00:34:27,01:40:03,04:17:30"


- video: sevadus/2020-10/782398211
  title: "Discussing Doctors - Sevadus - Oct. 26, 2020"
  t_start: "00:34:27"
  t_end: "01:17:56"


# ===========================================
# ===========================================


- video: sevadus/2020-10/783437801
  title: "Discussing Twitch VODs (part 2) - Sevadus - Oct. 27, 2020"
  t_start: "00:18:06,03:30:01"
  t_end: "03:26:34,04:07:27"

- video: sevadus/2020-10/784420040
  title: "Discussing Twitch VODs (part 3) - Sevadus - Oct. 28, 2020"
  t_start: "00:17:13,02:48:10,03:10:29"
  t_end: "02:17:12,03:07:26,04:47:10"

- video: sevadus/2020-10/784420040
  title: "Matt Watches AMD Announcement - Sevadus - Oct. 28, 2020"
  t_start: "02:18:08"
  t_end: "02:47:55"

# ===========================================
# ===========================================

- video: sevadus/2020-10/785970328
  title: "Shucking Hard Drives (part 1) - Sevadus - Oct. 29, 2020"
  t_start: "00:03:58"
  t_end: "01:13:04"

- video: sevadus/2020-10/785970328
  title: "Shucking Hard Drives (part 2) - Sevadus - Oct. 30, 2020"
  t_start: "00:28:41,02:50:46"
  t_end: "02:32:42,03:41:55"

- video: sevadus/2020-10/785970328
  title: "Matt Watches Random Videos - Sevadus - Oct. 30, 2020"
  t_start: "03:44:58"
  t_end: "04:35:55"


# ===========================================
# ===========================================


- video: sevadus/2020-11/790760313
  title: "Discussing Twitch VODs (part 4) - Sevadus - Nov. 03, 2020"
  t_start: "00:23:27,01:38:14,1:48:24,02:02:23,03:42:44"
  t_end: "00:33:09,1:45:03,02:01:32,02:36:39,04:41:07"

- video: sevadus/2020-11/790760313
  title: "Random Youtube Videos - Sevadus - Nov. 03, 2020"
  t_start: "00:36:04,1:45:03,02:36:39"
  t_end: "01:38:14,1:48:24,03:42:41"


# ===========================================
# ===========================================

- video: sevadus/2020-11/791719976
  title: "2020 Election Discussions (part 1) - Sevadus - Nov. 04, 2020"
  t_start: "00:13:34,00:52:15,03:39:58"
  t_end: "00:40:07,03:17:29,05:35:03"

- video: sevadus/2020-11/791719976
  title: "Novo.tv Discussion - Sevadus - Nov. 04, 2020"
  t_start: "00:40:24"
  t_end: "00:52:15"

# ===========================================
# ===========================================


- video: sevadus/2020-11/792714879
  title: "Dry Erase Wall (part 1) - Sevadus - Nov. 05, 2020"
  t_start: "00:17:29,01:42:47"
  t_end: "00:49:42,01:43:07"

- video: sevadus/2020-11/792714879
  title: "Watching Norway Train Live Stream - Sevadus - Nov. 05, 2020"
  t_start: "00:53:02"
  t_end: "01:43:09"

- video: sevadus/2020-11/792714879
  title: "Discussing Twitch VODs (part 5) - Sevadus - Nov. 05, 2020"
  t_start: "01:43:07"
  t_end: "01:45:35"

- video: sevadus/2020-11/792714879
  title: "2020 Election Discussions (part 2) - Sevadus - Nov. 05, 2020"
  t_start: "01:45:35,02:04:12,02:28:57"
  t_end: "02:02:45,02:24:39,02:49:07"

- video: sevadus/2020-11/792714879
  title: "Standing Desks Discussions (part 1) - Sevadus - Nov. 05, 2020"
  t_start: "02:03:40,02:24:44"
  t_end: "02:02:45,02:28:57"

# ===========================================
# ===========================================

- video: sevadus/2020-11/793744069
  title: "2020 Election Discussions (part 3) - Sevadus - Nov. 06, 2020"
  t_start: "00:12:56,00:50:49,01:33:11,03:18:41,03:40:16,04:06:39"
  t_end: "00:33:47,01:24:46,02:19:29,03:21:03,03:43:49,04:20:49"

- video: sevadus/2020-11/793744069
  title: "Standing Desks Discussions (part 2) - Sevadus - Nov. 06, 2020"
  t_start: "02:40:22,03:21:05,03:46:11,04:20:57,04:56:08"
  t_end: "03:18:41,03:40:16,03:57:09,04:41:57,05:02:17"

- video: sevadus/2020-11/793744069
  title: "Matt Discovers Tea - Sevadus - Nov. 06, 2020"
  t_start: "04:42:44"
  t_end: "04:56:08"

# ===========================================
# ===========================================



