

# https://dev.twitch.tv/console/apps
client_id: xxxxxxxxxxxxxx
client_secret: xxxxxxxxxxxxxx

# https://pushover.net/
pushover_enable: false
pushover_user_key: xxxxxxxxxxxxxx
pushover_app_key: xxxxxxxxxxxxxx

