

yt_creds: 'sodapoppin_creds.json'
yt_secrets: 'sodapoppin_secrets.json'

yt_template: 'soda_template.txt'

tags:
  - 'sodapoppin'
  - 'twitch'
  - 'vod'
  - 'streamer'
  - 'chance morris'
  - 'chance'
  - 'soda'
  - 'sodapoppintv'
  - 'wow'
  - 'games'
  - 'live'
  - 'live stream'
  - 'variety'
  - 'vr stream'
  - 'vr chat'
  - 'gta rp'

